name: ReleaseCI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release to S3
        run:  bash scripts/pipeline/release.sh "test-video-upload-with-github-action" "cypress/images2.zip" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "images2.zip"
