name: ReleaseCI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release to S3
        run:  bash scripts/pipeline/release.sh "test-video-upload-with-github-action" "cypress/videos3.zip" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "videos3.zip"
